/*
 * generated by Xtext
 */
package de.hajoeichler.jenkins;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JobConfigRuntimeModule extends de.hajoeichler.jenkins.AbstractJobConfigRuntimeModule {

}
