/*
* generated by Xtext
*/
package de.hajoeichler.jenkins.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JobConfigOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
