/*
 * generated by Xtext
 */
package de.hajoeichler.jenkins.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JobConfigUiModule extends de.hajoeichler.jenkins.ui.AbstractJobConfigUiModule {
	public JobConfigUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
