/*
* generated by Xtext
*/
package de.hajoeichler.jenkins.ui.contentassist;

import de.hajoeichler.jenkins.ui.contentassist.AbstractJobConfigProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JobConfigProposalProvider extends AbstractJobConfigProposalProvider {

}
